### ISSUE TITLE
Removed vars stay defined after a hot-reload

### ISSUE THREAD

**Issue by gnl** [thheller/shadow-cljs#258]
When hot-reloading code with shadow-cljs, vars which have been removed or renamed remain defined, as if the whole namespace was pasted into a REPL. When hot-reloading with figwheel, this is not the case. 

This is a problem when renaming or removing tests from a namespace, for example, the old ones still get executed with `run-tests` and I believe the figwheel behaviour here makes more sense. Can we get the same with shadow-cljs or at least make it optional?

**Comment by thheller** [comment]
Fixed this yesterday. Should work fine in `2.3.4`.

I don't think however that `figwheel` actually removes the vars client-side. `cljs.test/run-tests` is macro based so the removal just happens on the compiler side. Either way the behavior should now be the same in `shadow-cljs`.

**Comment by gnl** [comment]
I upgraded to 2.3.4 this morning and just reproduced this again:
```clojure
(def foo 123)
```
Save, hot-reload, evaluate in REPL:
```
foo
=> 123
```
Then in the file:
```clojure
;(def foo 123)
```
Save, hot-reload, REPL:
```clojure
foo
=> 123
```

**Comment by thheller** [comment]
And this is different in figwheel?

**Comment by gnl** [comment]
Yup, although now I notice that it still gets evaluated, but there's a compiler warning that it's undeclared, so not quite sure how that works exactly. Here's the REPL log with hot-reloads between each evaluation - first undefined, then defined, then removed.

```clojure
ClojureScript 1.10.238
dev:cljs.user=> (in-ns 're-frame-scratchpad.main)
nil
dev:re-frame-scratchpad.main=> foo
----  Compiler Warning on   <cljs form>   line:1  column:1  ----

  Use of undeclared Var re-frame-scratchpad.main/foo

  1  foo
     ^---

----  Compiler Warning  ----
nil
dev:re-frame-scratchpad.main=> foo
123
dev:re-frame-scratchpad.main=> foo
----  Compiler Warning on   <cljs form>   line:1  column:1  ----

  Use of undeclared Var re-frame-scratchpad.main/foo

  1  foo
     ^---

----  Compiler Warning  ----
123
dev:re-frame-scratchpad.main=>
```

**Comment by gnl** [comment]
To add to this - hot-reloads are also somewhat slower in `figwheel`, not sure if that's related. But clearly something works differently under the hood.

**Comment by thheller** [comment]
Ah, ok. Guess the compiler should reset the analyzer data when recompiling. Currently it just merges because thats the desired behavior in the REPL. Will adjust that.

Resetting the client side would be very tricky to do and probably not worth the effort.

**Comment by gnl** [comment]
If this makes things slower though, it might make sense to make it opt-in, because I can't think of many cases where this might be practically relevant other than testing and who knows what macro-magic, so most people would probably prefer the performance.

But if it isn't a trade off, even better.

**Comment by gnl** [comment]
Then again, this might hide refactoring issues and lead to weird bugs like something calling an old function, which still works, but shouldn't. Maybe best to ditch it altogether.

**Comment by thheller** [comment]
Resetting the `ns` is definitely the correct thing to do. Released as `2.3.5`. It won't affect reload times at all.

**Comment by gnl** [comment]
Behaviour seems unchanged.

```
=== Version
cli:            2.3.5
jar-version:    2.3.5
config-version: 2.3.5
```

Cleaned the build including `.shadow-cljs` before restarting everything to make sure this isn't a stale-something issue, but same thing. `foo` still gets resolved after being commented out in the source and a hot-reload, no warning, no nothing.
